//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mp3infp.rc
//
#define IDS_PAGE_MP3ID3V1_COUNT_OVER    1
#define IDS_PAGE_MP3ID3V1_COUNT         2
#define IDS_PAGE_THIS_READONLY          3
#define IDS_PAGE_MP3ID3V1_NOTFOUND_ID3  4
#define IDS_PAGE_CAN_NOT_OPEN           5
#define IDS_PAGE_MP3RIFF_BROKEN_RIFF    6
#define IDS_CAN_NOT_CREATE_TEMP_FILE    7
#define IDS_PAGE_MP3RIFF_CONV_MP3       8
#define IDS_PAGE_MP3RIFF_CONV_RMP       9
#define IDS_PAGE_MP3ID3V1_DEL_ID3TAG    10
#define IDS_PAGE_MP3ID3V1_MAKE_ID3TAG   11
#define IDS_PAGE_MP3ID3V1_CAN_NOT_DEL   12
#define IDS_PAGE_MP3ID3V11_COUNT_OVER   13
#define IDS_PAGE_MP3ID3V11_COUNT        14
#define IDS_PAGE_MP3ID3V2_CANNOT_WRITE  15
#define IDS_PAGE_MP3ID3V2_MAKE_ID3TAG   16
#define IDS_PAGE_MP3ID3V2_DEL_ID3TAG    17
#define IDS_PAGE_MP3ID3V2_CAN_NOT_MAKE  18
#define IDS_PAGE_MP3RIFF_CAN_NOT_MAKE   19
#define IDS_MEMERROR                    20
#define IDS_INFOTIP_NOTINFO             21
#define IDS_PAGE_MP3RIFF_CAN_NOT_MAKE2  22
#define IDS_PAGE_MP3ID3V2_CAN_NOT_MAKE2 23
#define IDS_NO_COMPRESS                 24
#define IDS_NO_VIDEO_STREAM             24
#define IDS_NO_AUDIO_STREAM             25
#define IDS_PAGE_VQF_BROKEN             26
#define IDS_CPL_NAME                    29
#define IDS_CPL_INFO                    30
#define IDS_CPL_CAPTION                 31
#define IDS_CAN_NOT_HTMLHELP_OPEN       32
#define IDS_UNKNOWN                     33
#define IDS_COMCTL32_INFO               34
#define IDS_PAGE_BROKEN                 35
#define IDS_INFOTIP_MAXLINE_OVER        36
#define IDS_PLEASE_TAG_NAME             37
#define IDS_OGG_BAD_CHAR                38
#define IDS_USER_ABORT                  39
#define IDS_OVER_2G                     39
#define IDS_LANGUAGE_NAME               40
#define IDS_LANGUAGE_VER                41
#define IDS_RELOAD_CPL                  42
#define IDS_TRANSLATOR                  43
#define IDS_AVI_UNCODE                  44
#define IDS_LANG_VER_ERROR              45
#define IDS_VIEW_PROP                   46
#define IDD_WRITE_PROGRESS              104
#define IDD_SETUP                       109
#define IDD_SETUP_MP3                   110
#define IDD_SETUP_WAVE                  111
#define IDD_SETUP_AVI                   112
#define IDD_SETUP_VQF                   113
#define IDC_EDIT_COPYRIGHT              1001
#define IDC_CHECK_ADD_CONTEXTMENU       1004
#define IDC_STATIC_NOT_MP3              1005
#define IDC_CHECK_FULLPATH              1006
#define IDC_CHECK_COLUMN_8_3            1007
#define IDC_ICON1                       1008
#define IDC_EDIT_CMT                    1009
#define IDC_EDIT_LIST                   1009
#define IDC_EDIT_COP                    1010
#define IDC_EDIT_TRACK                  1010
#define IDC_EDIT_ENG                    1011
#define IDC_EDIT_COMP                   1011
#define IDC_EDIT_RAT                    1012
#define IDC_EDIT_SRC                    1012
#define IDC_EDIT_URL                    1012
#define IDC_EDIT_URL1                   1013
#define IDC_RADIO_ID3                   1013
#define IDC_EDIT_ENC                    1013
#define IDC_EDIT_URL2                   1014
#define IDC_RADIO_SI                    1014
#define IDC_EDIT_ENC2                   1014
#define IDC_EDIT_PRD                    1015
#define IDC_EDIT_ART                    1016
#define IDC_EDIT_NAM                    1017
#define IDC_EDIT_CRD                    1018
#define IDC_EDIT_FILE                   1018
#define IDC_EDIT_GNR                    1019
#define IDC_EDIT_TRK                    1020
#define IDC_EDIT_SFT                    1020
#define IDC_EDIT_ORGART                 1020
#define IDC_STATIC_CMT                  1021
#define IDC_STATIC_COP                  1022
#define IDC_STATIC_CMT2                 1022
#define IDC_EDIT_ID3VER                 1022
#define IDC_STATIC_URL1                 1023
#define IDC_STATIC_ENG                  1023
#define IDC_STATIC_COMP                 1023
#define IDC_STATIC_CMT3                 1023
#define IDC_STATIC_FILE                 1023
#define IDC_STATIC_URL2                 1024
#define IDC_STATIC_SRC                  1024
#define IDC_STATIC_URL                  1024
#define IDC_STATIC_CMT4                 1024
#define IDC_STATIC_PRD                  1025
#define IDC_STATIC_ART                  1026
#define IDC_STATIC_NAM                  1027
#define IDC_STATIC_CRD                  1028
#define IDC_STATIC_GNR                  1029
#define IDC_STATIC_TRK                  1030
#define IDC_STATIC_SFT                  1030
#define IDC_STATIC_ORGART               1030
#define IDC_STATIC_CMT5                 1030
#define IDC_STATIC_ENC                  1031
#define IDC_EDIT_FILENAME               1032
#define IDC_STATIC_ENC2                 1033
#define IDC_STATIC_FORMAT               1034
#define IDC_STATIC_TIME                 1035
#define IDC_STATIC_FORMAT_              1036
#define IDC_STATIC_TIME_                1037
#define IDC_BUTTON_ID3DEL               1039
#define IDC_BUTTON_RIFFDEL              1040
#define IDC_BUTTON_REW                  1044
#define IDC_BUTTON_PLAY                 1045
#define IDC_BUTTON_PAUSE                1046
#define IDC_BUTTON_STOP                 1047
#define IDC_BUTTON_FFW                  1049
#define IDC_STATIC_COPYRIGHT            1050
#define IDC_STATIC_WINAMP               1051
#define IDC_STATIC_A1                   1052
#define IDC_STATIC_A2                   1053
#define IDC_STATIC_PATH                 1057
#define IDC_STATIC_SIG                  1059
#define IDC_STATIC_RAT                  1060
#define IDC_STATIC_SEEKABLE             1061
#define IDC_STATIC_BROADCAST            1062
#define IDC_STATIC_IS_PROTECTED         1063
#define IDC_STATIC_IS_TRUSTED           1064
#define IDC_STATIC_SAVE                 1065
#define IDC_STATIC_TRACK                1071
#define IDC_STATIC_LBA                  1072
#define IDC_STATIC_MSF                  1073
#define IDC_STATIC_DISCID               1074
#define IDC_STATIC_SIZE                 1075
#define IDC_EDIT_TITLE                  1088
#define IDC_EDIT_DSICTITLE              1089
#define IDC_EDIT_ARTIST                 1090
#define IDC_LIST                        1092
#define IDC_HELPVIEW                    1094
#define IDC_STATIC_ID3GUIDE             1095
#define IDC_SETUP                       1096
#define IDC_URL_JUMP                    1097
#define IDC_RADIO_INI                   1098
#define IDC_RADIO_MDB                   1099
#define IDC_CHECK_AOT                   1100
#define IDC_STATIC_ETC_INFO             1102
#define IDC_BUTTON_DEL_VALUE            1106
#define IDC_BUTTON_ADD_VALUE            1107
#define IDC_LIST_VALUE                  1109
#define IDC_PROGRESS1                   1110
#define IDC_STATIC_FORMAT_INFO          1111
#define IDC_STATIC_AUDIO_INFO           1112
#define IDC_STATIC_SIZE_INFO            1113
#define IDS_COLUMN_DESC_TITLE           2001
#define IDS_COLUMN_DESC_ARTIST          2002
#define IDS_COLUMN_DESC_ALBUM           2003
#define IDS_COLUMN_DESC_COMMENT         2004
#define IDS_COLUMN_DESC_GENRE           2005
#define IDS_COLUMN_DESC_DATE            2006
#define IDS_COLUMN_DESC_AUDIO_FORMAT    2007
#define IDS_COLUMN_DESC_VIDEO_FORMAT    2008
#define IDS_COLUMN_DESC_TIME            2009
#define IDS_COLUMN_DESC_TRACK           2010
#define IDS_COLUMN_DESC_SIZE            2011
#define IDS_COLUMN_DESC_8_3             2012
#define IDS_COLUMN_DESC_TAGTYPE         2013
#define IDS_COLUMN_DESC_AVIVER          2014
#define IDS_COLUMN_DESC_EXTENSION       2015
#define IDS_COLUMN_TITLE                2101
#define IDS_COLUMN_ARTIST               2102
#define IDS_COLUMN_ALBUM                2103
#define IDS_COLUMN_COMMENT              2104
#define IDS_COLUMN_GENRE                2105
#define IDS_COLUMN_DATE                 2106
#define IDS_COLUMN_AUDIO_FORMAT         2107
#define IDS_COLUMN_VIDEO_FORMAT         2108
#define IDS_COLUMN_TIME                 2109
#define IDS_COLUMN_TRACK                2110
#define IDS_COLUMN_SIZE                 2111
#define IDS_COLUMN_8_3                  2112
#define IDS_COLUMN_TAGTYPE              2113
#define IDS_COLUMN_AVIVER               2114
#define IDS_COLUMN_EXTENSION            2115
#define IDS_DEF_INFOTIP_MP3_FORMAT      3001
#define IDS_DEF_INFOTIP_WAVE_FORMAT     3002
#define IDS_DEF_INFOTIP_AVI_FORMAT      3003
#define IDS_DEF_INFOTIP_VQF_FORMAT      3004
#define IDS_DEF_INFOTIP_WMA_FORMAT      3005
#define IDS_DEF_INFOTIP_OGG_FORMAT      3006
#define IDS_DEF_INFOTIP_APE_FORMAT      3007
#define IDS_DEF_INFOTIP_INF_MP3_FORMAT  3201
#define IDS_DEF_INFOTIP_INF_WAVE_FORMAT 3202
#define IDS_DEF_INFOTIP_INF_AVI_FORMAT  3203
#define IDS_DEF_INFOTIP_INF_VQF_FORMAT  3204
#define IDS_DEF_INFOTIP_INF_WMA_FORMAT  3205
#define IDS_DEF_INFOTIP_INF_OGG_FORMAT  3206
#define IDS_DEF_INFOTIP_INF_APE_FORMAT  3207
#define IDC_COPY_FROM_ID3V2             5000
#define IDC_COPY_FROM_RIFF              5001
#define IDB_STOP                        5001
#define IDC_BUTTON_DEL_TAG              5002
#define IDB_PAUSE                       5002
#define IDC_BUTTON_MAKE_TAG             5003
#define IDB_PLAY                        5003
#define IDB_REW                         5004
#define IDB_FFW                         5005
#define IDC_CHECK_PROP_ENABLE           5005
#define IDC_CHECK_ID3V1SCMPX_GENRE      5009
#define IDC_CHECK_INFOTIP_ENABLE        5011
#define IDC_EDIT_RIFF_SOFT              5012
#define IDD_DIALOG_OGG_EXTTAG           5015
#define IDC_COPY_FROM_ID3V1             5018
#define IDC_STATIC_VER_INFO             5019
#define IDC_STATIC_FORMAT_V_            5020
#define IDC_STATIC_FORMAT_A_            5021
#define IDC_STATIC_FORMAT_A             5022
#define IDC_STATIC_FORMAT_V             5023
#define IDC_EDIT_SBJ                    5024
#define IDC_CHECK_SELECT_DRIVE          5025
#define IDC_CHECK_DISABLE_FDD           5026
#define IDC_CHECK_DISABLE_REMOVABLE     5027
#define IDC_CHECK_DISABLE_CDROM         5028
#define IDC_CHECK_DISABLE_NETWORK       5029
#define IDC_EDIT_NAME                   5030
#define IDC_EDIT_VALUE                  5031
#define IDC_STATIC_AVI_VER              5032
#define IDC_DEFAULT                     6001
#define IDI_ID3V2                       6002
#define IDC_EDIT_INFOTIP_FORMAT         6002
#define IDC_EDIT_INFOTIP_INFO           6003
#define IDC_COLUMN_ENABLE               6004
#define IDC_STATIC_INFOTIP_FORMAT       6007
#define IDC_STATIC_SOFT_DEFAULT         6008
#define IDC_SAVE_TIMESTAMP              6012
#define IDC_RADIO_PATH1                 6014
#define IDC_RADIO_PATH2                 6015
#define IDC_RADIO_PATH3                 6016
#define IDD_PAGE_MP3_ID3V1              20564
#define IDD_PAGE_MP3_ID3V2              20567
#define IDD_PAGE_MP3_RMP                20568
#define IDD_PAGE_CDA                    20569
#define IDD_PAGE_AUDIO_CD               20570
#define IDD_PAGE_VQF                    20571
#define IDD_PAGE_WMA                    20572
#define IDD_PAGE_AVI                    20573
#define IDD_PAGE_WAVE                   20574
#define IDD_SETUP_WMA                   20575
#define IDD_SETUP_M3U                   20576
#define IDD_PAGE_M3U                    20577
#define IDD_PAGE_OGG                    20578
#define IDD_SETUP_OGG                   20579
#define IDD_PAGE_APE                    20581

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        6016
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         6014
#define _APS_NEXT_SYMED_VALUE           6013
#endif
#endif
